[build]
  functions = "functions"
  # This tells Netlify to look inside the "public" folder for your website.
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
