[build]
  functions = "functions"
  # This tells Netlify your index.html is in the main root folder. THIS IS THE FIX.
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
